### ISSUE TITLE
[Support]:  Stray .eld files hanging around

### ISSUE THREAD

**Issue by ddoherty03** [progfolio/elpaca#207]
### Confirmation

- [X] I have read the documentation and need clarification.
- [X] I have searched previous issues to see if my question is a duplicate.
- [ ] I am  checking these without reading them.
- [X] I have checked the Elpaca github wiki to see if my issue is covered.

### Elpaca Version

Elpaca 86d995a HEAD -> master
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)
 of 2023-08-07
git --version:  git version 2.34.1

### Operating System

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

### Description

On every startup, I get the following warnings:

```
⛔ Warning (emacs): Error reading "/home/ded/.emacs.d/elpaca/cache/melpa.eld" into memory: (end-of-file "/home/ded/.emacs.d/eln-cache/29.1-59da9703/elpaca-menu-melpa-854c5235-a48a3e7d.eln")
⛔ Warning (emacs): Error reading "/home/ded/.emacs.d/elpaca/cache/gnu-devel-elpa.eld" into memory: (end-of-file "/home/ded/.emacs.d/eln-cache/29.1-59da9703/elpaca-menu-elpa-bce4e0d6-ac9ecf65.eln")
⛔ Warning (emacs): Error reading "/home/ded/.emacs.d/elpaca/cache/gnu-elpa.eld" into memory: (end-of-file "/home/ded/.emacs.d/eln-cache/29.1-59da9703/elpaca-menu-elpa-bce4e0d6-ac9ecf65.eln")
⛔ Warning (emacs): Error reading "/home/ded/.emacs.d/elpaca/cache/non-gnu-devel-elpa.eld" into memory: (end-of-file "/home/ded/.emacs.d/eln-cache/29.1-59da9703/elpaca-menu-elpa-bce4e0d6-ac9ecf65.eln")
⛔ Warning (emacs): Error reading "/home/ded/.emacs.d/elpaca/cache/non-gnu-elpa.eld" into memory: (end-of-file "/home/ded/.emacs.d/eln-cache/29.1-59da9703/elpaca-menu-elpa-bce4e0d6-ac9ecf65.eln")
```

They seem to be related to native compile and elpaca, but even if I delete them, as they are cache files, they get re-created in the same badly-formed way.

Any ideas what is going on here?

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a bug report.
That was a bug that slipped in when I was optimizing Elpaca's file reading macro.
Should be fixed as of: https://github.com/progfolio/elpaca/commit/eb79f7012e1517de838f96f48af2fa32e8e22617 

Updating Elpaca should fix the issue.
Let me know if that works for you.

**Comment by ddoherty03** [comment]
OK, I tried to update elpaca itself with these intructions: [https://github.com/progfolio/elpaca/issues/205](url), but I don't seem to have the `elpaca-merge` command.  And doing the update without it didn't fix the issue.

**Comment by ddoherty03** [comment]
Nicholoas, I take that back.  After deleting the existing cache files and restarting, the issue went away, so many thanks.  Is there supposed to be an `elpaca-merge` command, though?

**Comment by progfolio** [comment]
I'm assuming you've got the new commands worked out. If not just leave a comment and we can re-open this issue. Thanks.
