### ISSUE TITLE
[Bug/Support]: "End of file during parsing" error: how to see whole log, including commands?

### ISSUE THREAD

**Issue by garyo** [progfolio/elpaca#303]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 43ec2d8 grafted, HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-w64-mingw32)
 of 2024-04-08
git --version:  git version 2.44.0.windows.1

### Operating System

Windows 11

### Description

I'm getting errors building a few packages. Not sure how to track them down because the log doesn't have the actual subprocess command executed to build:

```
vertico [MELPA|GNU-devel ELPA]
VERTical Interactive COmpletion

source: MELPA
url: https://github.com/minad/vertico
menu item recipe:
( :package "vertico"
 :repo "minad/vertico"
 :files (:defaults "extensions/vertico-*.el")
 :fetcher github
 :source "MELPA")
full recipe:
( :package "vertico" 
 ;; Inherited from declaration.
 :files (:defaults "extensions/*")
 ;; Inherited from elpaca-order-functions.
 :depth 1
 :inherit t
 :protocol https
 ;; Inherited from elpaca-menu-item.
 :source "MELPA"
 :fetcher github
 :repo "minad/vertico")
dependencies: 
  emacs  >= 27.1
  compat >= 29.1.4.4
dependents: nil
installed version: 1.8 1def56a
statuses:
  (failed autoloads linking unblocked ref-checked-out unthrottled blocked queue-throttled unthrottled blocked queue-throttled queued)
files:
  $REPOS/vertico/extensions/vertico-buffer.el      → $BUILDS/vertico/vertico-buffer.el
  $REPOS/vertico/extensions/vertico-directory.el   → $BUILDS/vertico/vertico-directory.el
  $REPOS/vertico/extensions/vertico-flat.el        → $BUILDS/vertico/vertico-flat.el
  $REPOS/vertico/extensions/vertico-grid.el        → $BUILDS/vertico/vertico-grid.el
  $REPOS/vertico/extensions/vertico-indexed.el     → $BUILDS/vertico/vertico-indexed.el
  $REPOS/vertico/extensions/vertico-mouse.el       → $BUILDS/vertico/vertico-mouse.el
  $REPOS/vertico/extensions/vertico-multiform.el   → $BUILDS/vertico/vertico-multiform.el
  $REPOS/vertico/extensions/vertico-quick.el       → $BUILDS/vertico/vertico-quick.el
  $REPOS/vertico/extensions/vertico-repeat.el      → $BUILDS/vertico/vertico-repeat.el
  $REPOS/vertico/extensions/vertico-reverse.el     → $BUILDS/vertico/vertico-reverse.el
  $REPOS/vertico/extensions/vertico-suspend.el     → $BUILDS/vertico/vertico-suspend.el
  $REPOS/vertico/extensions/vertico-unobtrusive.el → $BUILDS/vertico/vertico-unobtrusive.el
  $REPOS/vertico/vertico.el                        → $BUILDS/vertico/vertico.el
log:
  [2024-05-02 09:33:03] Package queued
  [2024-05-02 09:33:03] Continued by: elpaca--process
  [2024-05-02 09:33:03] elpaca-queue-limit exceeded
  [2024-05-02 09:33:03] Continued by: elpaca--finalize
  [2024-05-02 09:33:03] elpaca-queue-limit exceeded
  [2024-05-02 09:33:04] Continued by: elpaca--finalize
  [2024-05-02 09:33:04] Continued by: elpaca--configure-remotes
  [2024-05-02 09:33:04] Continued by: elpaca--checkout-ref
  [2024-05-02 09:33:04] Continued by: elpaca--dispatch-build-commands
  [2024-05-02 09:33:04] Continued by: elpaca--queue-dependencies
  [2024-05-02 09:33:04] No external dependencies
  [2024-05-02 09:33:04] Checking dependency versions
  [2024-05-02 09:33:04] Continued by: elpaca--check-version
  [2024-05-02 09:33:04] Linking build files
  [2024-05-02 09:33:04] Continued by: elpaca--link-build-files
  [2024-05-02 09:33:04] Build files linked
  [2024-05-02 09:33:04] Generating autoloads: c:/Users/garyo/AppData/Roaming/.config/emacs/elpaca/builds/vertico
  [2024-05-02 09:33:04]   End of file during parsing
  [2024-05-02 09:33:04] Subprocess error (see previous log entries)
```

I set `elpaca-verbosity` to 100 but don't see anything more in that log.

**Comment by garyo** [comment]
I wonder if it could be related to this error regarding `generated-autoload-file` being redefined as dynamic?
```
% emacs --batch --eval '(let ((generated-autoload-file "autoloads.el")) (update-directory-autoloads "builds/vertico
"))'

Error: error ("Defining as dynamic an already lexical var" generated-autoload-file)
  (defvar generated-autoload-file nil "File into which to write autoload definitions.\nA Lisp file can set this in its local variables section to make\nits autoloads go somewhere else.\n\nIf this is a relative file name, the directory is determined as\nfollows:\n - If a Lisp file defined `generated-autoload-file' as a\n   file-local variable, use its containing directory.\n - Otherwise use the \"lisp\" subdirectory of `source-directory'.\n\nThe autoload file is assumed to contain a trailer starting with a\nFormFeed character.")
  require(loaddefs-gen)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\207" [require lisp-mode lisp-mnt cl-lib loaddefs-gen] 2)
  (update-directory-autoloads "builds/vertico")
  (let ((generated-autoload-file "autoloads.el")) (update-directory-autoloads "builds/vertico"))
  eval((let ((generated-autoload-file "autoloads.el")) (update-directory-autoloads "builds/vertico")) t)
  command-line-1(("--eval" "(let ((generated-autoload-file \"autoloads.el\")) (update-directory-autoloads \"builds/vertico\"))"))
  command-line()
  normal-top-level()
Defining as dynamic an already lexical var: generated-autoload-file
```

whereas this version without the `let` binding works for me:
```
% emacs --batch --eval '(progn (setq generated-autoload-file "autoloads.el") (update-directory-autoloads "builds/ve
rtico"))'
Package autoload is deprecated
  INFO     Scraping files for autoloads.el...
  INFO     Scraping files for autoloads.el...done
```

It looks to me like elpaca's `elpaca-generate-autoloads` uses the let-binding method, so maybe that's causing it but the error is suppressed, or it could be something else. Note that I am using a bleeding-edge emacs built from source.

**Comment by garyo** [comment]
I'm not 100% certain but doing this in my shell after the first elpaca pass with all the autoload failures seems to help:
```
garyo@tower1  (~/.config/emacs/elpaca/builds [main])  4:38PM 4200=>
% for d in *(/); do emacs --batch --eval "(loaddefs-generate \"$d\" \"$d/$d-autoloads.el\")"; done
  INFO     Scraping files for loaddefs...
  INFO     Scraping files for loaddefs...done
  INFO     Scraping files for loaddefs...
  INFO     Scraping files for loaddefs...done
...
```
then I restart emacs and things seem to go better.

**Comment by progfolio** [comment]
> I set `elpaca-verbosity` to 100 but don't see anything more in that log.

Sorry about that.
The entry is logged just after the process is kicked off.
In this case, the error beats the log to the punch.
That should be fixed on the master branch now.

> Error: error ("Defining as dynamic an already lexical var" generated-autoload-file)

Do you get the same error with a very simple configuration using `elpaca-test`?

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :init (elpaca (vertico :wait t))
  (elpaca-test-log "#unique"))
```

> It's not what I suggested above -- elpaca is correctly `defvar`ing
> `generated-autoload-file`. Still investigating... many packages have this error
> on my machine. Sometimes retrying them helps.

Yes, it should be defvar'd in elpaca.el.

> I'm not 100% certain but doing this in my shell after the first elpaca pass with all the autoload failures ("end of file during parsing") seems to help:

> ```
> garyo@tower1  (~/.config/emacs/elpaca/builds [main])  4:38PM 4200=>
> % for d in *(/); do emacs --batch --eval "(loaddefs-generate \"$d\" \"$d/$d-autoloads.el\")"; done
  > INFO     Scraping files for loaddefs...
  > INFO     Scraping files for loaddefs...done
  > INFO     Scraping files for loaddefs...
  > INFO     Scraping files for loaddefs...done
> ...


> Then I restart emacs and things seem to go better.

That may or may not work. When a package's build-dir is already on disk, Elpaca takes an optimistic path to reduce startup time. In that case only `elpaca--pre-built-steps` are run.
So it may just be skipping the issue. You could try a different operation like ` lpaca-rebuild`, which should attempt to regenerate the autoloads, after a restart to see if you hit the same error.

**Comment by garyo** [comment]
> The entry is logged just after the process is kicked off.
In this case, the error beats the log to the punch.
That should be fixed on the master branch now.

Hmm, no difference in the logs with elpaca 06ee3a6. Just "End of file during parsing" after "Generating autoloads".

> Do you get the same error with a very simple configuration using elpaca-test?

Wow, I love your test harness!!! Here's the results:


<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :init (elpaca (vertico :wait t))
  (elpaca-test-log "#unique"))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>06ee3a6 grafted, HEAD -> master, origin/master, origin/HEAD</td>
<tr><td>installer</td><td>0.7</td>
<tr><td>emacs</td><td>GNU Emacs 30.0.50 (build 1, x86_64-w64-mingw32) of 2024-04-08</td>
<tr><td>git</td><td>git version 2.44.0.windows.1</td>
</table>
</details>

<details open><summary>Output</summary>

```emacs-lisp


Error: end-of-file nil

  command-line-1(("--eval" "(setq debug-on-error t after-init-time nil)" "--eval" "(setq user-emacs-directory \"d:/tmp/elpaca.K94MA9) --eval (run-hooks" "'before-init-hook) -l ./init.el --eval (setq" "after-init-time" "(current-time)) --eval (run-hooks" "'after-init-hook) --eval (run-hooks" "'emacs-startup-hook) --eval (message" "\n" "Test" "Env\n) --eval (elpaca-version" "'message)"))

  command-line()

  normal-top-level()

End of file during parsing

```
</details>

From that output, I can see there's a missing escaped close-quote after the tmpdir. But I don't think it's getting to the point of trying to install vertico (or any of the other packages that fail -- about 50 fail for me, so it's not about the package itself). Also note this only happens on Windows. Maybe it's a path thing due to something like the "d:/" drive name?

The command seems to be OK (properly quoted) in `elpaca-test--make-process` :
```
("d:/emacs/emacs/bin/emacs" "--debug-init" "--batch" "-Q" #1="--eval" "(setq debug-on-error t after-init-time nil)" #1# "(setq user-emacs-directory \"d:/tmp/elpaca.iShFzl\")" "--eval" "(run-hooks 'before-init-hook)" "-l" "./init.el" "--eval" "(setq after-init-time (current-time))" "--eval" "(run-hooks 'after-init-hook)" "--eval" "(run-hooks 'emacs-startup-hook)" "--eval" "(message \"\n Test Env\n\")" "--eval" "(elpaca-version 'message)")
```

so I don't yet see where the trailing quote in the tmpdir is getting stripped off. (If that is indeed the problem.)

**Comment by progfolio** [comment]
> Hmm, no difference in the logs with elpaca [06ee3a6](https://github.com/progfolio/elpaca/commit/06ee3a6918596fbb80733737c945b65ea9039664). Just "End of file during parsing" after "Generating autoloads".

Ah, it was actually being over-written in the log due to me not accounting for DOS/Linux line ending differences in `elpaca--process-filter`. Should be fixed (for real this time) on master. I'm seeing the commands in the log in my Win10 VM now.

> > Do you get the same error with a very simple configuration using elpaca-test?
> 
> Wow, I love your test harness!!! Here's the results:

Thank you. It's been very handy for working out bugs.

> From that output, I can see there's a missing escaped close-quote after the tmpdir. But I don't think it's getting to the point of trying to install vertico (or any of the other packages that fail -- about 50 fail for me, so it's not about the package itself). Also note this only happens on Windows. Maybe it's a path thing due to something like the "d:/" drive name? Or a Windows arg-quoting issue when creating subprocesses? (That would be an Emacs bug I guess...)
> 
> The command seems to be OK (properly quoted) in `elpaca-test--make-process` :
> 
> ```
> ("d:/emacs/emacs/bin/emacs" "--debug-init" "--batch" "-Q" #1="--eval" "(setq debug-on-error t after-init-time nil)" #1# "(setq user-emacs-directory \"d:/tmp/elpaca.iShFzl\")" "--eval" "(run-hooks 'before-init-hook)" "-l" "./init.el" "--eval" "(setq after-init-time (current-time))" "--eval" "(run-hooks 'after-init-hook)" "--eval" "(run-hooks 'emacs-startup-hook)" "--eval" "(message \"\n Test Env\n\")" "--eval" "(elpaca-version 'message)")
> ```
> 
> so I don't yet see where the trailing quote in the tmpdir is getting stripped off. (If that is indeed the problem.)

Interesting! Indeed, I get the same error in my VM. I'm not sure what's causing that, but at least we've gotten to what seems like the root of the issue.

> Maybe it's a path thing due to something like the "d:/" drive name? Or a Windows arg-quoting issue when creating subprocesses? (That would be an Emacs bug I guess...)

Here's my hypothesis:
Windows file-path separator is being interpreted as an escape character "\" in the printed command.
It escapes the closing quote for that string.
That seems to make sense with what we're observing.

**Comment by progfolio** [comment]
Here's a test independent of Elpaca:

```emacs-lisp
(make-process
 :name "*test*"
 :filter (lambda (process output) (message "%S" output))
 :sentinel (lambda (process event) (message "%S" event))
 :command (list (elpaca--emacs-path)
                "--batch" "--eval" (format "(print %S)" user-emacs-directory)))
```

On my Linux machine I get:

```
#<process *test*>
"
\"~/.emacs.d/\"
"
"finished
"
```

On Windows I get the error we're seeing.
So it's either a bug with how Emacs handles command line args,
or perhaps there's a better way to format the command string.
I'll try reporting upstream tomorrow and see if anyone has any insight.

**Comment by progfolio** [comment]
Noting this here:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Asynchronous-Processes.html

> Function: make-process &rest args ¶
> ...
> :coding coding
>
>  If coding is a symbol, it specifies the coding system to be used for both reading and writing of data from and to the connection. If coding is a cons cell (decoding . encoding), then decoding will be used for reading and encoding for writing. The coding system used for encoding the data written to the program is also used for encoding the command-line arguments (but not the program itself, whose file name is encoded as any other file name; see file-name-coding-system).
> 
> If coding is nil, the default rules for finding the coding system will apply. See Default Coding Systems.

I noticed you've changed default-process-coding-system in your config.
However, I still get the same error with `emacs -q` on Windows.
Still unsure whether this is Elpaca's or Emacs's bug.

**Comment by progfolio** [comment]
> However, I still get the same error with `emacs -q` on Windows, so I don't think that's the issue. Still unsure whether this is Elpaca's or Emacs's bug.

Apologies, must've not been running the test in the instance I thought I was last night.
With `emacs -q` I no longer get the error.

**Comment by garyo** [comment]
I concur, your non-elpaca test works for me with `emacs -Q`. I tried setting `(setq default-process-coding-system '(utf-8-unix . utf-8-unix))` before running the test in `emacs -Q` and it still succeeds.

There is some very hairy quoting code in emacs's `w32proc.c` but at the moment I can't debug into that.

**Comment by progfolio** [comment]
> I concur, your non-elpaca test works for me with `emacs -Q`. I tried setting
> `(setq default-process-coding-system '(utf-8-unix . utf-8-unix))` before running
> the test in `emacs -Q` and it still succeeds.

Good idea. I'll try and isolate a minimal reproduction case.
  
> There is some very hairy quoting code in emacs's `w32proc.c` but at the moment I
> can't debug into that.

Once we have a solid reproduction case, if I'm confident it's not something on Elpaca's end, I'll open a bug report upstream.
Eli uses Windows, so he may have some knowledge of the inner workings there.

> Is it just me or does RET in the *elpaca-log* buffer no longer show the details
> for that order?
> It seems that `elpaca-info` thinks
> `interactive` is nil when I edebug into `elpaca-info` and hit RET on a log line.
> Passing `t` as 3rd arg from `elpaca-ui-info` seems to fix it for me.

Good catch and sorry about that!
I refactored `elpaca-info` to make it easier to use in tests, and as you've noticed, missed that call site in `elpaca-ui-info`.
Should be fixed on master now.

> Is there any way to fully expand that log buffer to show all lines

You can add the "#verbosity" search tag to your search query to temporarily set `elpaca-verbosity` to a maximum in the log buffer.
The `elpaca-info` buffer should normally display the whole log, too.

> or dump the log elsewhere?

I recently refactored `elpaca-log` to make it easier to use from lisp programs as well.
The following should write the full log to a file: 

``` emacs-lisp
(with-temp-buffer 
  (insert (elpaca-log ".*"))
  (write-file "/tmp/test.log"))
```

**Comment by garyo** [comment]
I seem to have a fix for this issue! Since forever (maybe 15 or 20 years anyway), I've had this in my init file: `(setq w32-quote-process-args ?\")`
If I remove that, my elpaca setup runs to completion. 
I have no idea why I had to have that, all those years ago; I expect the default value of `t` is fine.
I also can't explain why you *can* repro it, unless you have the same setting.

**Comment by progfolio** [comment]
> I seem to have a fix for this issue! Since forever (maybe 15 or 20 years anyway), I've had this in my init file: `(setq w32-quote-process-args ?\")` If I remove that, my elpaca setup runs to completion. I have no idea why I had to have that, all those years ago; I expect the default value of `t` is fine. 

Aha! I figured it might've been a user option.

> I also can't explain why you _can_ repro it, unless you have the same setting.

I was running your config on Windows :).

**Comment by garyo** [comment]
thanks!

**Comment by progfolio** [comment]
> thanks!

Thank you!
Let me know if that also takes care of https://github.com/progfolio/elpaca/issues/302 for you.
